const {
  createRunOncePlugin,
  withAppDelegate,
  withEntitlementsPlist,
  withInfoPlist,
  withPodfileProperties,
} = require("@expo/config-plugins");

const PLUGIN_NAME = "withCarPlay";
const PLUGIN_VERSION = "2.0.0";

const CARPLAY_ROLE = "CPTemplateApplicationSceneSessionRoleApplication";
const PHONE_ROLE = "UIWindowSceneSessionRoleApplication";
const CARPLAY_CONFIGURATION_NAME = "Lumen-CarPlay";
const PHONE_CONFIGURATION_NAME = "Lumen-Phone";
// Flat Objective-C names, set by @objc on the Swift classes. Keep in sync with
// modules/carplay/ios/LumenCarPlaySceneDelegate.swift and CarPlayModule.swift.
const DELEGATE_CLASS = "LumenCarPlaySceneDelegate";
const PHONE_DELEGATE_CLASS = "LumenPhoneSceneDelegate";
const AUDIO_ENTITLEMENT = "com.apple.developer.carplay-audio";
const DEV_CLIENT_DEFAULT_URL_KEY = "DEV_CLIENT_DEFAULT_LAUNCHER_URL";
const DEV_LAUNCH_URL_BUILD_SETTING = "$(LUMEN_DEV_LAUNCH_URL)";
const BUILD_REACT_NATIVE_FROM_SOURCE_KEY = "ios.buildReactNativeFromSource";

const IMPORT_MARKER = "// @generated by withCarPlay: runtime import";
const STATE_BEGIN = "// @generated begin withCarPlay runtime state";
const STATE_END = "// @generated end withCarPlay runtime state";
const LAUNCH_BEGIN = "// @generated begin withCarPlay runtime launch";
const LAUNCH_END = "// @generated end withCarPlay runtime launch";
const HOST_BEGIN = "// @generated begin withCarPlay runtime host";
const HOST_END = "// @generated end withCarPlay runtime host";

const APP_DELEGATE_DECLARATION = "class AppDelegate: ExpoAppDelegate {";
const HOSTING_APP_DELEGATE_DECLARATION =
  "class AppDelegate: ExpoAppDelegate, LumenReactRuntimeHosting {";

const EXPO_RUNTIME_STATE = `${STATE_BEGIN}
  private var reactRootViewController: UIViewController?
  private var reactLaunchOptions: [UIApplication.LaunchOptionsKey: Any]?
  private var reactRuntimeStarted = false
  ${STATE_END}`;

const EXPO_STARTUP_PATTERN =
  /    let delegate = ReactNativeDelegate\(\)\n    let factory = ExpoReactNativeFactory\(delegate: delegate\)\n    delegate\.dependencyProvider = RCTAppDependencyProvider\(\)\n\n    reactNativeDelegate = delegate\n    reactNativeFactory = factory\n\n#if os\(iOS\) \|\| os\(tvOS\)\n    window = UIWindow\(frame: UIScreen\.main\.bounds\)\n    factory\.startReactNative\(\n      withModuleName: "main",\n      in: window,\n      launchOptions: launchOptions\)\n#endif/;

const EXPO_SCENE_INDEPENDENT_STARTUP = `    ${LAUNCH_BEGIN}
    reactLaunchOptions = launchOptions
    ensureReactRuntimeStarted()
    ${LAUNCH_END}`;

const RUNTIME_HOST_IMPLEMENTATION = `${HOST_BEGIN}
  /// Starts Expo and creates its main surface exactly once. The surface and
  /// controller deliberately exist before (and independently of) a phone
  /// UIWindow, which lets a cold CarPlay scene initialize JavaScript itself.
  func ensureReactRuntimeStarted() {
    dispatchPrecondition(condition: .onQueue(.main))
    guard !reactRuntimeStarted else { return }
    reactRuntimeStarted = true

    let delegate = ReactNativeDelegate()
    delegate.dependencyProvider = RCTAppDependencyProvider()
    delegate.didCreateRootViewController = { [weak self] controller in
      self?.reactRootViewController = controller
    }

    let factory = ExpoReactNativeFactory(delegate: delegate)
    reactNativeDelegate = delegate
    reactNativeFactory = factory

    NSLog("LUMENCP: starting shared React runtime")
    factory.startReactNative(
      withModuleName: "main",
      in: nil,
      launchOptions: reactLaunchOptions)

    guard let rootView = reactRootViewController?.view else {
      preconditionFailure("Expo did not create the retained React root view")
    }

    // Fabric normally flushes mounting transactions on the display beat of the
    // UIWindow containing the root. A CarPlay-only launch intentionally has no
    // phone window, so give the surface constraints and pump transactions while
    // the app bootstraps. More than one is required: providers such as the
    // persisted theme render an empty first commit, hydrate asynchronously, and
    // mount the real app in a later commit.
    rootView.frame = UIScreen.main.bounds
    rootView.setNeedsLayout()
    rootView.layoutIfNeeded()
    if let hostingView = rootView as? RCTSurfaceHostingProxyRootView,
       let surface = hostingView.surface as? NSObject {
      let surfaceProtocol = hostingView.surface
      DispatchQueue.global(qos: .userInitiated).async {
        let deadline = Date().addingTimeInterval(10)
        while surfaceProtocol.stage.rawValue & 8 == 0, Date() < deadline {
          Thread.sleep(forTimeInterval: 0.01)
        }
        guard surfaceProtocol.stage.rawValue & 8 != 0 else {
          NSLog("LUMENCP: retained surface did not reach its running stage")
          return
        }
        let selector = NSSelectorFromString("synchronouslyWaitFor:")
        typealias WaitForTransaction =
          @convention(c) (AnyObject, Selector, TimeInterval) -> Bool
        guard surface.responds(to: selector) else {
          NSLog("LUMENCP: retained surface cannot flush its initial transaction")
          return
        }
        let wait = unsafeBitCast(
          surface.method(for: selector),
          to: WaitForTransaction.self)
        var mountedTransactions = 0
        let pumpDeadline = Date().addingTimeInterval(18)
        while Date() < pumpDeadline {
          if wait(surface, selector, 0.5) {
            mountedTransactions += 1
            // synchronouslyWaitFor schedules its transaction onto main. This
            // sync block runs after it and supplies any follow-up layout pass
            // before waiting for the next React commit.
            DispatchQueue.main.sync {
              rootView.setNeedsLayout()
              rootView.layoutIfNeeded()
            }
          }
        }
        NSLog("LUMENCP: retained surface transaction pump mounted=%d", mountedTransactions)
      }
    } else {
      assertionFailure("Expo main root is not a Fabric surface")
    }

    precondition(
      reactRootViewController != nil,
      "Expo did not create the retained React root view controller")
  }

  /// Gives the retained React controller a scene-native window when the phone
  /// UI connects. No second surface, factory, or React host is created.
  func connectPhoneScene(_ windowScene: UIWindowScene) -> UIWindow {
    dispatchPrecondition(condition: .onQueue(.main))
    ensureReactRuntimeStarted()

    if let window, window.windowScene === windowScene {
      window.makeKeyAndVisible()
      return window
    }

    guard let reactRootViewController else {
      preconditionFailure("React runtime started without a root view controller")
    }

    window?.isHidden = true
    let sceneWindow = UIWindow(windowScene: windowScene)
    sceneWindow.rootViewController = reactRootViewController
    window = sceneWindow
    sceneWindow.makeKeyAndVisible()
    NSLog("LUMENCP: connected phone scene to shared React surface")
    return sceneWindow
  }

  func disconnectPhoneScene(_ windowScene: UIWindowScene) {
    dispatchPrecondition(condition: .onQueue(.main))
    guard let window, window.windowScene === windowScene else { return }
    window.isHidden = true
    window.rootViewController = nil
    self.window = nil
    NSLog("LUMENCP: disconnected phone scene; React runtime remains active")
  }
  ${HOST_END}`;

const DELEGATE_CONTROLLER_HOOK = `  ${HOST_BEGIN} delegate hook
  var didCreateRootViewController: ((UIViewController) -> Void)?

  override func createRootViewController() -> UIViewController {
    let controller = super.createRootViewController()
    didCreateRootViewController?(controller)
    return controller
  }
  ${HOST_END} delegate hook

`;

/**
 * Rewrites the stock Expo AppDelegate into a scene-independent React host.
 *
 * This intentionally matches the complete Expo startup stanza. A partial
 * match after an Expo template change is more dangerous than a failed
 * prebuild because it can silently create two React hosts or lose an Expo
 * delegate handler.
 */
function transformAppDelegate(contents) {
  const generatedMarkers = [STATE_BEGIN, LAUNCH_BEGIN, HOST_BEGIN];
  const markerCount = generatedMarkers.filter((marker) =>
    contents.includes(marker),
  ).length;

  if (markerCount > 0) {
    if (
      markerCount !== generatedMarkers.length ||
      !contents.includes(STATE_END) ||
      !contents.includes(LAUNCH_END) ||
      !contents.includes(HOST_END) ||
      !contents.includes(`${HOST_END} delegate hook`) ||
      !contents.includes(HOSTING_APP_DELEGATE_DECLARATION)
    ) {
      throw new Error(
        "withCarPlay found an incomplete generated runtime-host block in AppDelegate.swift. Run a clean Expo prebuild before retrying.",
      );
    }
    // Xcode 26 generates ExpoModulesProvider with explicit internal imports.
    // Keep our import at the same access level even when upgrading output
    // produced by an earlier version of this plugin.
    return contents.replace(
      "\nimport LumenCarPlay\n",
      "\ninternal import LumenCarPlay\n",
    );
  }

  if (!contents.includes(APP_DELEGATE_DECLARATION)) {
    throw new Error(
      "withCarPlay could not recognize Expo's AppDelegate declaration. The Expo iOS template may have changed; update the plugin before prebuilding.",
    );
  }
  if (!EXPO_STARTUP_PATTERN.test(contents)) {
    throw new Error(
      "withCarPlay could not recognize Expo's React startup block in AppDelegate.swift. The Expo iOS template may have changed; update the plugin before prebuilding.",
    );
  }
  if (
    !contents.includes(
      "class ReactNativeDelegate: ExpoReactNativeFactoryDelegate {",
    )
  ) {
    throw new Error(
      "withCarPlay could not find Expo's ReactNativeDelegate in AppDelegate.swift. The Expo iOS template may have changed; update the plugin before prebuilding.",
    );
  }
  if (!contents.includes("  // Linking API")) {
    throw new Error(
      "withCarPlay could not find the AppDelegate linking insertion point. The Expo iOS template may have changed; update the plugin before prebuilding.",
    );
  }

  let result = contents.replace(
    "import ReactAppDependencyProvider",
    `import ReactAppDependencyProvider\ninternal import LumenCarPlay\n${IMPORT_MARKER}`,
  );
  result = result.replace(
    APP_DELEGATE_DECLARATION,
    HOSTING_APP_DELEGATE_DECLARATION,
  );
  result = result.replace(
    "  var reactNativeFactory: RCTReactNativeFactory?",
    `  var reactNativeFactory: RCTReactNativeFactory?\n\n  ${EXPO_RUNTIME_STATE}`,
  );
  result = result.replace(EXPO_STARTUP_PATTERN, EXPO_SCENE_INDEPENDENT_STARTUP);
  result = result.replace(
    "  // Linking API",
    `  ${RUNTIME_HOST_IMPLEMENTATION}\n\n  // Linking API`,
  );
  result = result.replace(
    "class ReactNativeDelegate: ExpoReactNativeFactoryDelegate {\n",
    `class ReactNativeDelegate: ExpoReactNativeFactoryDelegate {\n${DELEGATE_CONTROLLER_HOOK}`,
  );

  return result;
}

function applyCarPlayInfoPlist(infoPlist) {
  const manifest = infoPlist.UIApplicationSceneManifest ?? {};
  const configurations = manifest.UISceneConfigurations ?? {};

  const existing = Array.isArray(configurations[CARPLAY_ROLE])
    ? configurations[CARPLAY_ROLE].filter(
        (entry) =>
          entry.UISceneConfigurationName !== CARPLAY_CONFIGURATION_NAME,
      )
    : [];
  const existingPhone = Array.isArray(configurations[PHONE_ROLE])
    ? configurations[PHONE_ROLE].filter(
        (entry) => entry.UISceneConfigurationName !== PHONE_CONFIGURATION_NAME,
      )
    : [];

  return {
    ...infoPlist,
    [DEV_CLIENT_DEFAULT_URL_KEY]:
      infoPlist[DEV_CLIENT_DEFAULT_URL_KEY] ?? DEV_LAUNCH_URL_BUILD_SETTING,
    UIApplicationSceneManifest: {
      ...manifest,
      // Two scenes are live at once whenever CarPlay is connected.
      UIApplicationSupportsMultipleScenes: true,
      UISceneConfigurations: {
        ...configurations,
        [PHONE_ROLE]: [
          ...existingPhone,
          {
            UISceneClassName: "UIWindowScene",
            UISceneConfigurationName: PHONE_CONFIGURATION_NAME,
            UISceneDelegateClassName: PHONE_DELEGATE_CLASS,
          },
        ],
        [CARPLAY_ROLE]: [
          ...existing,
          {
            UISceneClassName: "CPTemplateApplicationScene",
            UISceneConfigurationName: CARPLAY_CONFIGURATION_NAME,
            UISceneDelegateClassName: DELEGATE_CLASS,
          },
        ],
      },
    },
  };
}

function applyCarPlayPodfileProperties(properties) {
  return {
    ...properties,
    // The CarPlay compatibility fixes in patches/react-native+0.86.0.patch
    // modify React Native source. Expo's precompiled React-Core would bypass
    // them and crash when APIs enumerate CPTemplateApplicationScene as if it
    // were a UIWindowScene.
    [BUILD_REACT_NATIVE_FROM_SOURCE_KEY]: "true",
  };
}

/**
 * Declares the phone and CarPlay scenes and turns the generated Expo app
 * delegate into the shared, window-independent React runtime host.
 *
 * The `com.apple.developer.carplay-audio` entitlement is opt-in because Apple
 * grants it per app. Enable it only after approval.
 */
function withCarPlay(config, { audioEntitlement = false } = {}) {
  config = withPodfileProperties(config, (config) => {
    config.modResults = applyCarPlayPodfileProperties(config.modResults);
    return config;
  });

  config = withInfoPlist(config, (config) => {
    config.modResults = applyCarPlayInfoPlist(config.modResults);
    return config;
  });

  config = withAppDelegate(config, (config) => {
    if (config.modResults.language !== "swift") {
      throw new Error(
        `withCarPlay requires a Swift AppDelegate, received ${config.modResults.language}.`,
      );
    }
    config.modResults.contents = transformAppDelegate(
      config.modResults.contents,
    );
    return config;
  });

  if (audioEntitlement) {
    config = withEntitlementsPlist(config, (config) => {
      config.modResults[AUDIO_ENTITLEMENT] = true;
      return config;
    });
  }

  return config;
}

const plugin = createRunOncePlugin(withCarPlay, PLUGIN_NAME, PLUGIN_VERSION);

module.exports = plugin;
// Export pure transforms for fixture tests. Expo still receives the run-once
// plugin function as the CommonJS default export.
module.exports.transformAppDelegate = transformAppDelegate;
module.exports.applyCarPlayInfoPlist = applyCarPlayInfoPlist;
module.exports.applyCarPlayPodfileProperties = applyCarPlayPodfileProperties;
module.exports.constants = {
  CARPLAY_ROLE,
  PHONE_ROLE,
  DEV_CLIENT_DEFAULT_URL_KEY,
  DEV_LAUNCH_URL_BUILD_SETTING,
  BUILD_REACT_NATIVE_FROM_SOURCE_KEY,
};
