const {
  createRunOncePlugin,
  withAppDelegate,
  withEntitlementsPlist,
  withInfoPlist,
} = require("@expo/config-plugins");

const PLUGIN_NAME = "withSiriMedia";
const PLUGIN_VERSION = "1.0.0";

const SIRI_ENTITLEMENT = "com.apple.developer.siri";
const PLAY_MEDIA_INTENT = "INPlayMediaIntent";
const MUSIC_CATEGORY = "INMediaCategoryMusic";
const IMPORT_MARKER = "// @generated by withSiriMedia: imports";
const HANDLER_BEGIN = "// @generated begin withSiriMedia intent handler";
const HANDLER_END = "// @generated end withSiriMedia intent handler";
const LINKING_MARKER = "  // Linking API";

function uniqueStrings(value, required) {
  const items = Array.isArray(value)
    ? value.filter((item) => typeof item === "string")
    : [];
  return [...new Set([...items, required])];
}

function applySiriInfoPlist(
  infoPlist,
  usageDescription = "Use Siri to find and play music from your Lumen library.",
) {
  return {
    ...infoPlist,
    NSSiriUsageDescription:
      infoPlist.NSSiriUsageDescription ?? usageDescription,
    INIntentsSupported: uniqueStrings(
      infoPlist.INIntentsSupported,
      PLAY_MEDIA_INTENT,
    ),
    INSupportedMediaCategories: uniqueStrings(
      infoPlist.INSupportedMediaCategories,
      MUSIC_CATEGORY,
    ),
  };
}

function applySiriEntitlements(entitlements) {
  return {
    ...entitlements,
    [SIRI_ENTITLEMENT]: true,
  };
}

function transformAppDelegate(contents) {
  const hasBegin = contents.includes(HANDLER_BEGIN);
  const hasEnd = contents.includes(HANDLER_END);
  const hasImportMarker = contents.includes(IMPORT_MARKER);

  if (hasBegin || hasEnd || hasImportMarker) {
    if (!(hasBegin && hasEnd && hasImportMarker)) {
      throw new Error(
        "withSiriMedia found an incomplete generated AppDelegate block. Run a clean Expo prebuild before retrying.",
      );
    }
    return contents;
  }

  if (!contents.includes("import ReactAppDependencyProvider")) {
    throw new Error(
      "withSiriMedia could not find Expo's AppDelegate import anchor. The Expo iOS template may have changed; update the plugin before prebuilding.",
    );
  }
  if (!contents.includes(LINKING_MARKER)) {
    throw new Error(
      "withSiriMedia could not find Expo's AppDelegate linking insertion point. The Expo iOS template may have changed; update the plugin before prebuilding.",
    );
  }

  let result = contents.replace(
    "import ReactAppDependencyProvider",
    `import ReactAppDependencyProvider\nimport Intents\ninternal import LumenSiriMedia\n${IMPORT_MARKER}`,
  );

  const handler = `  ${HANDLER_BEGIN}
  func application(
    _ application: UIApplication,
    handlerFor intent: INIntent
  ) -> Any? {
    guard intent is INPlayMediaIntent else { return nil }
    return LumenPlayMediaIntentHandler.shared
  }
  ${HANDLER_END}

`;
  result = result.replace(LINKING_MARKER, `${handler}${LINKING_MARKER}`);
  return result;
}

function withSiriMedia(config, options = {}) {
  const usageDescription = options.usageDescription;

  config = withInfoPlist(config, (config) => {
    config.modResults = applySiriInfoPlist(
      config.modResults,
      usageDescription,
    );
    return config;
  });

  config = withEntitlementsPlist(config, (config) => {
    config.modResults = applySiriEntitlements(config.modResults);
    return config;
  });

  config = withAppDelegate(config, (config) => {
    if (config.modResults.language !== "swift") {
      throw new Error(
        `withSiriMedia requires a Swift AppDelegate, received ${config.modResults.language}.`,
      );
    }
    config.modResults.contents = transformAppDelegate(
      config.modResults.contents,
    );
    return config;
  });

  return config;
}

const plugin = createRunOncePlugin(
  withSiriMedia,
  PLUGIN_NAME,
  PLUGIN_VERSION,
);

module.exports = plugin;
module.exports.applySiriEntitlements = applySiriEntitlements;
module.exports.applySiriInfoPlist = applySiriInfoPlist;
module.exports.transformAppDelegate = transformAppDelegate;
module.exports.constants = {
  MUSIC_CATEGORY,
  PLAY_MEDIA_INTENT,
  SIRI_ENTITLEMENT,
};
